# ==================================================
# C?U HÌNH DATABASE NEON (POSTGRESQL)
# ==================================================

# ??a ch? k?t n?i (?ã l?y t? link b?n g?i)
spring.datasource.url=jdbc:postgresql://ep-soft-fog-ahw4xkyh-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require

# Tên ??ng nh?p
spring.datasource.username=neondb_owner

# M?t kh?u
spring.datasource.password=npg_f9JnT4yulZXq

# Driver cho PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# T? ??ng t?o b?ng n?u ch?a có (R?t ti?n cho l?n ch?y ??u tiên)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==================================================
# CÁC C?U HÌNH C? (GI? NGUYÊN)
# ==================================================
spring.thymeleaf.cache=false
vnpay.tmnCode=TIOQTNPZ
vnpay.hashSecret=2PNG41Z07E84F32Z948JGCBCKJK25NIJ
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# L?u ý: Khi nào deploy xong nh? s?a localhost thành link web th?t
vnpay.returnUrl=http://localhost:8080/vnpay-return

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB